### ISSUE TITLE
Text Domain not loading translated strings.

### ISSUE THREAD

**Issue by Vinsanity** [3five/Custom-User-Profile-Photo#1]
Need to add `load_plugin_textdomain( 'custom-user-profile-photo', false, dirname( plugin_basename( __FILE__ ) ) . '/languages/' );`

**Comment by jmichaelward** [comment]
Note also that the latest pull request includes additional strings to be translated via the `_e()` method. There was some loose content in the markup that has since been wrapped in this function.

**Comment by Vinsanity** [comment]
Thanks! 
I've also got a spanish translation to add from a gentleman that sent us pot files back in December.
